### ISSUE TITLE
a bug: all icons and videos disappea after end of full indexing. Windows 11

### ISSUE THREAD

**Issue by AlesUshakou** [vinavfx/stock_manager#1]
However, there is a bug: if you wait for full indexing, then all icons and videos disappear. If you stop without waiting for the end of indexing, then everything is saved
![image](https://github.com/vinavfx/stock_manager/assets/164145472/d15feb11-80cc-4b09-990c-00c274a2e0b0)
The result if I stop indexing:
![image](https://github.com/vinavfx/stock_manager/assets/164145472/9a06214c-027b-45fa-b662-2cf670c9eba5)

**Comment by vinavfx** [comment]
Hello, when I have time I will look at it since I use Linux and it works for me. I still need to know the version of Nuke you are using and the format of the stock you are using or better if you share 1 of your stock with me to test.

**Comment by AlesUshakou** [comment]
¡Hola! 
I have a nuke 15.v4. The problem is not in stock files, but in the fact that the script erases all the images and previews created by it if I wait for the end of indexing.:
![image](https://github.com/vinavfx/stock_manager/assets/164145472/d80708db-9164-4660-8aaa-c8dcf86f5c67)


If I press the stop button, then all the work done by these will be saved:
![image](https://github.com/vinavfx/stock_manager/assets/164145472/6b1f14d5-25ad-441f-a97a-cc73f79ecca8)

**Comment by vinavfx** [comment]
![Screenshot at 2024-05-01 11-29-28](https://github.com/vinavfx/stock_manager/assets/40272695/1fa0ee9c-7845-46b8-9e8e-d036002ad865)
momentarily comment the lines of "garbage_remove()" in the indexing.py file on line 131, that is to delete the leftover files and for some reason it is not working for you and it deletes everything. later I will correct it well.

**Comment by AlesUshakou** [comment]
It's working now. Thank you for your work!

**Comment by huqqaazx** [comment]
After installing it, I started Nuke, but it did not create a stock_manager_indexing folder in the .nuke directory. After opening Nuke, I could not see the thumbnails in stock_manager. What is going on? Thank you.
![1726763582993](https://github.com/user-attachments/assets/bfefd116-ba3c-457a-b2f9-d155a283f9a9)
![Uploading 1726763635028.jpg…]()
